<?php
// $Id$

/**
 * Implementation of hook_ctools_plugin_api().
 */
function bulats_boxes_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function bulats_boxes_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'bulats_boxes') .'/plugins';
  $info['ctools_content'] = array(
  	'title' => 'Bulats Box',
    'handler' => array(
      'parent' => 'box',
      'class' => 'bulats_boxes',
      'file' => 'bulats_boxes.inc',
      'path' => $path,
    ),
  );
  return $info;
}

