<?php
// $Id$

/**
 * Implementation of hook_ctools_plugin_api().
 */
function bulats_boxes_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function bulats_boxes_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'boxes') . '/plugins';
  $info['box'] = array(
    'handler' => array(
      'class' => 'boxes_box',
      'file' => 'boxes_box.inc',
      'path' => drupal_get_path('module', 'boxes') . '/plugins',
    ),
  );
  $info['bulats'] = array(
    'title' => 'Bulats Box',
    'handler' => array(
      'parent' => 'box',
      'class' => 'boxes_bulats',
      'file' => 'bulats_boxes.inc',
      'path' => $path,
    ),
  );
  return $info;
}

